[nodes]
n0: _
n1: _
n2: _
n3: _
n4: _
n5: _
n6: _
n7: _
n8: _
n9: _

[links]
n0:n2 delay=10ms bw=10
n0:n3 delay=10ms bw=10
n0:n6 delay=10ms bw=10
n0:n7 delay=10ms bw=10
n0:n8 delay=10ms bw=10
n1:n2 delay=10ms bw=10
n1:n4 delay=10ms bw=10
n1:n5 delay=10ms bw=10
n2:n3 delay=5ms bw=10
n2:n4 delay=10ms bw=10
n3:n6 delay=10ms bw=10
n3:n8 delay=10ms bw=10
n3:n9 delay=10ms bw=10
n4:n5 delay=10ms bw=10
n4:n7 delay=10ms bw=10
n8:n9 delay=10ms bw=10
